"""Generate a dependency-free HTML dashboard from the active MySQL release."""
from pathlib import Path
import html,json,sys
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT))
from src.load.load_mysql import connect,env
def rows(q,sql,args=()):q.execute(sql,args);return q.fetchall()
def main():
    cnx=connect(env(ROOT/".env"));q=cnx.cursor();q.execute("SELECT release_id,release_key,row_count,activated_at FROM release_registry WHERE is_active=TRUE");rid,rkey,total,activated=q.fetchone();total=int(total);statuses=[(s,int(n)) for s,n in rows(q,"SELECT status,SUM(ticket_count) FROM ads_daily_status WHERE release_id=%s GROUP BY status ORDER BY 2 DESC",(rid,))];top=[(c,int(n)) for c,n in rows(q,"SELECT complaint_type,ticket_count FROM ads_complaint WHERE release_id=%s ORDER BY ticket_count DESC LIMIT 12",(rid,))];monthly=[(m,int(n)) for m,n in rows(q,"SELECT MONTH(created_day),SUM(ticket_count) FROM ads_daily_status WHERE release_id=%s GROUP BY MONTH(created_day) ORDER BY 1",(rid,))];cnx.close()
    model=json.loads((ROOT/"reports"/"p6"/"closure_model.json").read_text(encoding="utf-8"));roc=model["test"]["roc_auc"];bars=''.join(f'<div class="barrow"><span>{m:02d}月</span><div style="width:{n/max(x[1] for x in monthly)*100:.1f}%"></div><b>{n:,}</b></div>' for m,n in monthly);status_rows=''.join(f'<tr><td>{html.escape(s)}</td><td>{n:,}</td><td>{n/total:.2%}</td></tr>' for s,n in statuses);top_rows=''.join(f'<tr><td>{i}</td><td>{html.escape(c)}</td><td>{n:,}</td></tr>' for i,(c,n) in enumerate(top,1))
    doc=f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>城市公共服务工单数据工程看板</title><style>body{{font-family:Segoe UI,Arial,sans-serif;background:#f5f7fb;color:#162033;margin:0}}main{{max-width:1100px;margin:32px auto;padding:0 20px}}h1{{margin-bottom:4px}}.meta{{color:#657087}}.cards{{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin:24px 0}}.card,.panel{{background:white;border-radius:12px;padding:20px;box-shadow:0 2px 12px #23314d12}}.big{{font-size:30px;font-weight:700}}.grid{{display:grid;grid-template-columns:1.2fr 1fr;gap:16px}}table{{width:100%;border-collapse:collapse}}th,td{{padding:9px;border-bottom:1px solid #e7ebf2;text-align:left}}.barrow{{display:grid;grid-template-columns:42px 1fr 85px;gap:10px;align-items:center;margin:9px 0}}.barrow div{{height:18px;background:#246bfd;border-radius:4px}}.barrow b{{font-size:12px}}footer{{margin:20px 0;color:#657087}}@media(max-width:750px){{.cards,.grid{{grid-template-columns:1fr}}}}</style></head><body><main><h1>城市公共服务工单 · 2025 数据工程看板</h1><div class="meta">发布 {html.escape(rkey)} · 激活时间 {activated} · 范围 [2025-01-01, 2026-01-01)</div><section class="cards"><div class="card"><div class="meta">真实唯一工单</div><div class="big">{total:,}</div></div><div class="card"><div class="meta">数据月份</div><div class="big">12</div></div><div class="card"><div class="meta">活动发布</div><div class="big">1</div></div><div class="card"><div class="meta">时效模型 ROC-AUC</div><div class="big">{roc:.3f}</div></div></section><section class="grid"><div class="panel"><h2>每月创建量</h2>{bars}</div><div class="panel"><h2>当前状态</h2><table><tr><th>状态</th><th>数量</th><th>占比</th></tr>{status_rows}</table></div></section><section class="panel" style="margin-top:16px"><h2>问题类型 Top 12</h2><table><tr><th>#</th><th>问题类型</th><th>工单数</th></tr>{top_rows}</table></section><footer>数据源：城市公共服务工单开放数据。工单数量不等同居民人数；关闭状态不代表居民满意度。</footer></main></body></html>'''
    out=ROOT/"dashboard"/"index.html";out.write_text(doc,encoding="utf-8");report={"release_key":rkey,"total_rows":total,"status_total":sum(x[1] for x in statuses),"month_total":sum(x[1] for x in monthly),"output":str(out),"checks_passed":sum(x[1] for x in statuses)==total==sum(x[1] for x in monthly)};(ROOT/"reports"/"p5"/"dashboard_build.json").write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding="utf-8");print(json.dumps(report,ensure_ascii=False,indent=2))
if __name__=="__main__":main()
