[mysqld]
basedir=E:/nyc311_runtime/mysql-8.4.11-winx64
datadir=E:/nyc311_runtime/mysql-data
port=3307
bind-address=127.0.0.1
mysqlx=0
character-set-server=utf8mb4
collation-server=utf8mb4_0900_ai_ci
secure-file-priv=E:/nyc311_runtime/import
local-infile=OFF
max_connections=50
innodb_buffer_pool_size=1G
log-error=E:/nyc311_runtime/log/mysql-error.log
pid-file=E:/nyc311_runtime/mysql.pid

[client]
host=127.0.0.1
port=3307
default-character-set=utf8mb4
