CREATE DATABASE IF NOT EXISTS nyc311 CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE nyc311;

CREATE TABLE IF NOT EXISTS pipeline_run (
    run_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    run_key VARCHAR(100) NOT NULL,
    run_type VARCHAR(30) NOT NULL,
    scope_start DATETIME(3) NULL,
    scope_end DATETIME(3) NULL,
    status VARCHAR(20) NOT NULL,
    source_rows BIGINT UNSIGNED NOT NULL DEFAULT 0,
    staged_rows BIGINT UNSIGNED NOT NULL DEFAULT 0,
    inserted_rows BIGINT UNSIGNED NOT NULL DEFAULT 0,
    updated_rows BIGINT UNSIGNED NOT NULL DEFAULT 0,
    unchanged_rows BIGINT UNSIGNED NOT NULL DEFAULT 0,
    rejected_rows BIGINT UNSIGNED NOT NULL DEFAULT 0,
    started_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    finished_at TIMESTAMP(3) NULL,
    error_message TEXT NULL,
    PRIMARY KEY (run_id),
    UNIQUE KEY uk_pipeline_run_key (run_key),
    KEY idx_pipeline_status_started (status, started_at),
    CONSTRAINT chk_pipeline_status CHECK (status IN ('RUNNING','SUCCEEDED','FAILED'))
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS staging_ticket (
    run_id BIGINT UNSIGNED NOT NULL,
    unique_key VARCHAR(32) NOT NULL,
    source_updated_at TIMESTAMP(3) NULL,
    created_date DATETIME(3) NOT NULL,
    closed_date DATETIME(3) NULL,
    agency VARCHAR(32) NOT NULL,
    agency_name VARCHAR(255) NULL,
    complaint_type VARCHAR(255) NOT NULL,
    descriptor VARCHAR(255) NULL,
    location_type VARCHAR(255) NULL,
    incident_zip VARCHAR(20) NULL,
    status VARCHAR(40) NOT NULL,
    due_date DATETIME(3) NULL,
    resolution_action_updated_date DATETIME(3) NULL,
    community_board VARCHAR(80) NULL,
    council_district VARCHAR(40) NULL,
    police_precinct VARCHAR(80) NULL,
    borough VARCHAR(40) NOT NULL,
    open_data_channel_type VARCHAR(40) NULL,
    latitude DECIMAL(10,7) NULL,
    longitude DECIMAL(10,7) NULL,
    content_hash BINARY(32) NOT NULL,
    quality_flags JSON NULL,
    PRIMARY KEY (run_id, unique_key),
    KEY idx_staging_unique_key (unique_key),
    CONSTRAINT fk_staging_run FOREIGN KEY (run_id) REFERENCES pipeline_run(run_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ticket_current (
    unique_key VARCHAR(32) NOT NULL,
    source_updated_at TIMESTAMP(3) NULL,
    created_date DATETIME(3) NOT NULL,
    closed_date DATETIME(3) NULL,
    agency VARCHAR(32) NOT NULL,
    agency_name VARCHAR(255) NULL,
    complaint_type VARCHAR(255) NOT NULL,
    descriptor VARCHAR(255) NULL,
    location_type VARCHAR(255) NULL,
    incident_zip VARCHAR(20) NULL,
    status VARCHAR(40) NOT NULL,
    due_date DATETIME(3) NULL,
    resolution_action_updated_date DATETIME(3) NULL,
    community_board VARCHAR(80) NULL,
    council_district VARCHAR(40) NULL,
    police_precinct VARCHAR(80) NULL,
    borough VARCHAR(40) NOT NULL,
    open_data_channel_type VARCHAR(40) NULL,
    latitude DECIMAL(10,7) NULL,
    longitude DECIMAL(10,7) NULL,
    content_hash BINARY(32) NOT NULL,
    quality_flags JSON NULL,
    first_seen_run_id BIGINT UNSIGNED NOT NULL,
    last_seen_run_id BIGINT UNSIGNED NOT NULL,
    warehouse_updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (unique_key),
    KEY idx_ticket_created (created_date),
    KEY idx_ticket_source_updated (source_updated_at),
    CONSTRAINT fk_ticket_first_run FOREIGN KEY (first_seen_run_id) REFERENCES pipeline_run(run_id),
    CONSTRAINT fk_ticket_last_run FOREIGN KEY (last_seen_run_id) REFERENCES pipeline_run(run_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ticket_observation (
    observation_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    unique_key VARCHAR(32) NOT NULL,
    run_id BIGINT UNSIGNED NOT NULL,
    content_hash BINARY(32) NOT NULL,
    source_updated_at TIMESTAMP(3) NULL,
    observed_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    status VARCHAR(40) NOT NULL,
    closed_date DATETIME(3) NULL,
    agency VARCHAR(32) NOT NULL,
    complaint_type VARCHAR(255) NOT NULL,
    borough VARCHAR(40) NOT NULL,
    PRIMARY KEY (observation_id),
    UNIQUE KEY uk_observation_version (unique_key, content_hash),
    KEY idx_observation_run (run_id),
    KEY idx_observation_unique_time (unique_key, observed_at),
    CONSTRAINT fk_observation_run FOREIGN KEY (run_id) REFERENCES pipeline_run(run_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS release_registry (
    release_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    release_key VARCHAR(100) NOT NULL,
    run_id BIGINT UNSIGNED NOT NULL,
    status VARCHAR(20) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    row_count BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    activated_at TIMESTAMP(3) NULL,
    PRIMARY KEY (release_id),
    UNIQUE KEY uk_release_key (release_key),
    KEY idx_release_active (is_active, status),
    CONSTRAINT fk_release_run FOREIGN KEY (run_id) REFERENCES pipeline_run(run_id),
    CONSTRAINT chk_release_status CHECK (status IN ('CANDIDATE','ACTIVE','REJECTED'))
) ENGINE=InnoDB;
